# Generated by Django 3.1 on 2020-09-12 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_auto_20200912_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='Category',
            new_name='category',
        ),
    ]
